### ISSUE TITLE
Whitelabel error page on http://localhost:30020/vehicles/City%20Truck

### ISSUE THREAD

**Issue by abhinavvsinhaa** [DickChesterwood/k8s-fleetman#44]
Got the following error, while trying to access position tracker on port 30020. Tried all arm64 releases, nothing seems to work!

<img width="1435" alt="Screenshot 2023-05-14 at 5 02 16 PM" src="https://github.com/DickChesterwood/k8s-fleetman/assets/76272472/b84344df-42bf-4768-9a1b-bcf71692a12c">

Command used for mapping the port:

> kubectl port-forward svc/fleetman-position-tracker 30020:8080

workloads.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: fleetman-queue-container
        image: richardchesterwood/k8s-fleetman-queue:release1-arm64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator-container
        image: richardchesterwood/k8s-fleetman-position-simulator:release1-arm64
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker-container
        image: richardchesterwood/k8s-fleetman-position-tracker:release1-arm64
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
```
services.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - name: http
    port: 8161
    nodePort: 30010
 
  - name: endpoint-for-messages
    port: 61616
 
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
  - name: rest-endpoint
    port: 8080
    nodePort: 30020
  type: NodePort
```

Environment details:
1. Operating System: MacOS Ventura 13.3.1
2. Docker version: 4.19.0
3. Minikube version: 1.30.1
