### ISSUE TITLE
left-hand panel empty with release1

### ISSUE THREAD

**Issue by jdevoo** [DickChesterwood/k8s-fleetman#47]
Hello Richard! I am enjoying your udemy course. It's the best introducing the key concepts instead of delving into kubelets and what not.
I arrived on ch. 11 deploying the complete set but Chromium (I am on Ubuntu) is not showing the data.
(Apologies if this is not the right place)

Below is some information about my setup.

Minikube version: v1.30.1
The console logs show websocket connection established.
Below is the output of kubectl get all
```
NAME                                      READY   STATUS    RESTARTS   AGE
pod/api-gateway-5bf5cfc887-8sc8h          1/1     Running   0          10m
pod/position-simulator-56686f95f8-bwm5d   1/1     Running   0          10m
pod/position-tracker-f5bfcf944-wlprt      1/1     Running   0          10m
pod/queue-5877c4c669-487sj                1/1     Running   0          10m
pod/webapp-586c6c87cd-m9db9               1/1     Running   0          10m

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                          AGE
service/fleetman-api-gateway   ClusterIP   10.101.68.20     <none>        8080/TCP                         10m
service/fleetman-queue         NodePort    10.104.40.70     <none>        8161:30010/TCP,61616:31517/TCP   10m
service/fleetman-webapp        NodePort    10.111.225.253   <none>        80:30080/TCP                     10m
service/kubernetes             ClusterIP   10.96.0.1        <none>        443/TCP                          23h
service/position-tracker       ClusterIP   10.109.151.103   <none>        8080/TCP                         10m

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/api-gateway          1/1     1            1           10m
deployment.apps/position-simulator   1/1     1            1           10m
deployment.apps/position-tracker     1/1     1            1           10m
deployment.apps/queue                1/1     1            1           10m
deployment.apps/webapp               1/1     1            1           10m

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/api-gateway-5bf5cfc887          1         1         1       10m
replicaset.apps/position-simulator-56686f95f8   1         1         1       10m
replicaset.apps/position-tracker-f5bfcf944      1         1         1       10m
replicaset.apps/queue-5877c4c669                1         1         1       10m
replicaset.apps/webapp-586c6c87cd               1         1         1       10m
```
Below is my yaml file
```
piVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: richardchesterwood/k8s-fleetman-queue:release1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  selector:
    matchLabels:
      app: position-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - name: http
    port: 8161
    nodePort: 30010
  - name: endpoint
    port: 61616
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: position-tracker
spec:
  selector:
    app: position-tracker
  ports:
  - name: http
    port: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8080
  type: ClusterIP
```

**Comment by jdevoo** [comment]
I noticed earlier issues in the simulator showing a bunch of these in the log
```
2023-05-26 14:05:40.655  WARN 1 --- [ool-1-thread-12] c.v.simulator.journey.Journey            : Queue unavailable - backing off 5000ms before retry
2023-05-26 14:05:40.937  WARN 1 --- [ool-1-thread-11] c.v.simulator.journey.Journey            : Queue unavailable - backing off 5000ms before retry
2023-05-26 14:05:41.733  WARN 1 --- [ool-1-thread-28] c.v.simulator.journey.Journey            : Queue unavailable - backing off 5000ms before retry
2023-05-26 14:05:41.970  WARN 1 --- [pool-1-thread-1] c.v.simulator.journey.Journey            : Queue unavailable - backing off 5000ms before retry
```
These disappeared after removing the NodePort and corresponding 30020 mapping from the fleetman-queue svc definition
```
---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - name: endpoint
    port: 61616
  type: ClusterIP

---

```
